import{a as S,i,S as b}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const q="47376168-762e2e3775122625ea22809a6",O="https://pixabay.com/api/";async function p(t,r=1,l=15){const s=`${O}?key=${q}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${l}`;try{return(await S.get(s)).data}catch{throw new Error("Failed to fetch images")}}function P(t){t.innerHTML=""}function y(t,r){const l=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:c,views:v,comments:w,downloads:E})=>`
      <a href="${e}" class="gallery__item">
        <div class="photo-card">
          <img src="${s}" alt="${o}" loading="lazy" />
          <div class="info">
            <li><h3>Likes</h3> <p>${c}</p></li>
            <li><h3>Views</h3> <p>${v}</p></li>
            <li><h3>Comments</h3> <p>${w}</p></li>
            <li><h3>Downloads</h3> <p>${E}</p></li>
          </div>
        </div>
      </a>
    `).join("");r.insertAdjacentHTML("beforeend",l)}const m=document.querySelector("#search-form"),f=document.querySelector(".gallery"),h=document.querySelector(".loader"),L=document.querySelector(".load-more");let d="",a=1,u=0,g;m.addEventListener("submit",async t=>{if(t.preventDefault(),d=m.elements.searchQuery.value.trim(),!d){i.warning({title:"Warning",message:"Please enter something into the search field!",position:"topRight",timeout:3e3});return}a=1,P(f),n(!0);try{const r=await p(d,a);if(n(!1),u=r.totalHits,r.hits.length===0){i.warning({title:"No results",message:"Sorry, no images found!"});return}i.info({title:"Results",message:`Found ${u} images.`}),y(r.hits,f),g=new b(".gallery a"),g.refresh(),$(u>a*15)}catch(r){n(!1),i.error({title:"Error",message:r.message})}});L.addEventListener("click",async()=>{a+=1,n(!0);try{const t=await p(d,a);n(!1),y(t.hits,f),g.refresh(),a*15>=u&&(i.info({title:"End",message:"You've reached the end of search results."}),$(!1))}catch(t){n(!1),i.error({title:"Error",message:t.message})}});function n(t){h.textContent=t?"Loading...":"",h.classList.toggle("is-hidden",!t)}function $(t){L.classList.toggle("is-hidden",!t)}
//# sourceMappingURL=index.js.map
